=== vdelachaux/4DPop-Macros/Build/Components/4DPop Macros.4dbase/Contents/Resources/macros.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--Grammar for 4th Dimension methods macros. 4D SA.-->

<!-- caret position after macro expansion -->
<!ELEMENT caret EMPTY>

<!-- placeholder for selection -->
<!ELEMENT selection EMPTY>

<!-- placeholder for operating system user name -->
<!ELEMENT user_os EMPTY>

<!-- placeholder for 4D user name -->
<!ELEMENT user_4d EMPTY>

<!-- placeholder for method name -->
<!ELEMENT method_name EMPTY>

<!-- placeholder for method path -->
<!ELEMENT method_path EMPTY>

<!-- placeholder for current time -->
<!-- format = 0 to 8 -->
<!ELEMENT time EMPTY>
<!ATTLIST time format CDATA #IMPLIED>

<!-- placeholder for current date -->
<!-- format = 0 to 6 -->
<!ELEMENT date EMPTY>
<!ATTLIST date format CDATA #IMPLIED>

<!-- placeholder for clipboard contents -->
<!-- index = 0 to 9 -->
<!ELEMENT clipboard EMPTY>
<!ATTLIST clipboard index CDATA #IMPLIED>

<!-- method contents -->
<!ELEMENT method (#PCDATA | user_os | user_4d | time | date | method_name | method_path | caret | selection | clipboard )*>

<!-- macro contents -->
<!ELEMENT text (#PCDATA | user_os | user_4d | time | date | method_name | method_path | caret | selection | method | clipboard )*>

<!-- macro -->
<!-- name = name as displayed in contextual menu -->
<!-- type_ahead_text = text to type to activate the macro using type ahead (default is the macro name) -->
<!-- type_ahead = should this macro be available using type ahead? (default is true) -->
<!-- note: if the macro contents uses the selection placeholder, it cannot be activated using type-ahead -->
<!-- in_menu = should this macro be displayed in contextual menu? (default is true) -->
<!-- method_event can be on_create, on_save, on_load, on_close, on_tab -->
<!-- version: if version is equal to 2, macro can use SET/GET MACRO PARAMETER method -->
<!ELEMENT macro (text?)>
<!ATTLIST macro
  name CDATA #REQUIRED
  type_ahead_text CDATA #IMPLIED
  type_ahead (true | false) "true"
  in_menu (true | false) "true"
  in_toolbar (true | false) "true"
  method_event CDATA #IMPLIED
  version CDATA #IMPLIED
>
<!-- a macro file contains macros -->
<!ELEMENT macros (#PCDATA | macro)*>

=== vdelachaux/4DPop-Macros/Build/Components/4DPop Macros.4dbase/Contents/Macros v2/4DPop_Macros.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE macros SYSTEM "http://www.4d.com/dtd/2007/macros.dtd" >

<!--
    4DPop macros - [EN]
    vincent@de-lachaux.net
-->

<macros>
    
    <!-- ******************************* TOOLS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Macro test/0" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>4DPop_TEST_Macros</method></text>
    </macro>
    
    <macro name="Replay the last macro run" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS</method></text>
    </macro>
    
    <macro name="Declarations.../$" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("Declarations";"<method_path/>")</method></text>
    </macro>
    
    <macro name="Compiler directive… /¢" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
         <text><method>_4DPop_MACROS("compiler_directive")</method></text>
    </macro>
    
    <macro name="Constant value…" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("constantValue")</method></text>
    </macro>
    
    <macro name="Find with Google" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("googleSearch")</method></text>
    </macro>
    
    <macro name="Make an archive" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("zipForShare")</method></text>
    </macro>
    
    <!-- ******************************* METHODS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
        
    <macro name="New method…/…" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_method" 
        version="2">        
        <text><method>_4DPop_MACROS("method-new")</method></text>        
    </macro>
        
    <macro name="Beautifier/§" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("Beautifier")</method></text>        
    </macro>
    
    <macro name="Remove blank lines/*" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("RemoveBlankLines")</method></text>        
    </macro>
    
    <!-- ******************************* COPY PASTE ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Scomber scombrus : lol">
        <text><method>_4DPop_MACROS("about")</method></text>
    </macro>
    
    <macro name="Copy with tokens"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_4DPop_MACROS("CopyWithTokens")</method></text>
    </macro>
    
    <macro name="Copy and replace/©" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("PasteAndKeepTarget")</method></text>
    </macro>
    
    <macro name="Special paste.../◊" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_p"
        version="2">
        <text><method>_4DPop_MACROS("SpecialPaste")</method></text>
    </macro>
    
    <macro name="Past a color expression" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_c"
        version="2">
        <text><method>_4DPop_MACROS("PasteColor")</method></text>
    </macro>
    
    <!-- ******************************* COMMENTS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="4d macro">
        <text>Maquereau 4D : <caret/></text>        
    </macro>

    <macro name="Comments/j"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_4DPop_MACROS("comment")</method></text>
    </macro>
    
    <macro name="Duplicate and comment/∂"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_4DPop_MACROS("duplicateAndComment")</method></text>
    </macro>
    
    <!-- ******************************* REFACTORING ******************************* -->
    <macro name="-" type_ahead="false"><text/></macro>
    
    <macro name="Conditional assertion/æ" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("Asserted")</method></text>
    </macro>
    
    <macro name="Convert to call with token" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("ConvertToCallWithToken")</method></text>
    </macro>
    
    <macro name="Dot notation" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("dot_notation")</method></text>
    </macro>
    
    <macro name="Choose" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("Choose")</method></text>        
    </macro>
    
    <macro name="EXECUTE METHOD" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("convert_to_execute")</method></text>        
    </macro>
    
    <macro name="EXECUTE FORMULA" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("convert_to_formula")</method></text>        
    </macro>
        
    <!-- ******************************* CONVERSIONS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Maquereau 4D : mdr">
        <text>Scomber scombrus : <caret/></text>
    </macro>
    
    <macro name="Convert to Hexa" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("convert_hexa")</method></text>
    </macro>
    
    <macro name="Convert to decimal" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("convert_decimal")</method></text>
    </macro>
    
    <macro name="-" type_ahead="false"><text/></macro>
    
    <macro name="Invert expression" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("invert_expression")</method></text>
    </macro>
    
    <macro name="-"  in_menu="true" type_ahead="false"><text/></macro>
    
</macros>

=== vdelachaux/4DPop-Macros/Resources/FR_US Looping & Branching.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE macros SYSTEM "http://www.4d.com/dtd/2007/macros.dtd" >
<macros>
        
    <!-- THE FOLLOWING MACROS ARE NOT DISPLAYED NOR IN THE MENU NOR IN THE TOOLBAR BUT AVAILABLE THRU TYPE AHEAD-->
    
    <macro  name="Si" in_menu="false" in_toolbar="false" type_ahead="true">
        <text>If(<caret/>)
            
                <selection/>
            
            Else
            
             // A "If" statement should never omit a "Else" statement  
            
            End if</text>
    </macro>
    
    <macro name="Au cas ou" in_menu="false" in_toolbar="false" type_ahead="true">
        <text>Case of
            //______________________________________________________
            :(<caret/>)
            
                <selection/>
            
            //______________________________________________________
            :(False)
            
            
            
            //______________________________________________________
            Else
            
            // A "Case of" statement should never omit a "Else" statement
      
            //______________________________________________________
            End case</text>
    </macro>
    
    <macro name="Tant que" in_menu="false" in_toolbar="false" type_ahead="true">
        <text>While(<caret/>)
            
            <selection/>
            
            End while</text>
    </macro> 
    
    <macro name="Boucle" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>For($i;1;<caret/>;1)
            
            <selection/>
            
            End for</text>
    </macro>
    
    <macro name="Repeter" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>Repeat
            
            <selection/>
            
            Until(<caret/>)</text>
    </macro>
    
    <macro name="Fin de si" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>End if</text>
    </macro>
    
    <macro name="Fin de boucle" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>End for</text>
    </macro>
    
    <macro name="Fin tant que" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>End while</text>
    </macro>
    
    <macro name="Fin de cas" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>End case</text>
    </macro>
    
    <macro name="Sinon" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>Else</text>
    </macro>
    
    <macro name="Jusque" in_menu="false" type_ahead="true" in_toolbar="false">
        <text>Until</text>
    </macro>
    
</macros>

=== vdelachaux/4DPop-Macros/Resources/fr.lproj/4DPop_Macros.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE macros SYSTEM "http://www.4d.com/dtd/2007/macros.dtd" >

<!--
    4DPop macros - [FR]
    vincent@de-lachaux.net
-->

<macros>
    
    <!-- ******************************* OUTILS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Test Macro/0" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>4DPop_TEST_Macros</method></text>        
    </macro>
    
    <macro name="Rejouer la dernière macro exécutée" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro</method></text>        
    </macro>
    
    <macro name="Déclarations.../$" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("Declarations";"<method_path/>")</method></text>        
    </macro>
    
    <macro name="Directive de compilation… /¢" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("compiler_directive")</method></text>
    </macro>
    
    <macro name="Valeur de la constante…" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("constantValue")</method></text>
    </macro>
    
    <macro name="Chercher avec Google" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("googleSearch")</method></text>
    </macro>
    
    <macro name="Faire une archive" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("zipForShare")</method></text>
    </macro>
    
    <!-- ******************************* METHODS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Nouvelle méthode…/…" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_method" 
        version="2">        
        <text><method>_runMacro("method-new")</method></text>        
    </macro>
    
    <macro name="Attributs de la méthode…" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_attributes" 
        version="2">        
        <text><method>_runMacro("method-attributes";"<method_path/>")</method></text>        
    </macro>
    
    <macro name="Beautifier/§" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("Beautifier")</method></text>        
    </macro>
    
    <macro name="Supprimer les lignes vides/*" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("RemoveBlankLines")</method></text>        
    </macro>
    
    <!-- ******************************* COPIER COLLER ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Scomber scombrus : lol">
        <text><method>_runMacro("about")</method></text>
    </macro>
    
    <macro name="Copie avec tokens"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_runMacro("CopyWithTokens")</method></text>
    </macro>
    
    <macro name="Copier et Remplacer/©" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("PasteAndKeepTarget")</method></text>        
    </macro>
    
    <macro name="Collage spécial.../◊" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_p" 
        version="2">        
        <text><method>_runMacro("SpecialPaste")</method></text>        
    </macro>
    
    <macro name="Coller une couleur" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_c" 
        version="2">        
        <text><method>_runMacro("PasteColor")</method></text>        
    </macro>  
    
    <!-- ******************************* COMMENTAIRES ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="4d macro">
        <text>Maquereau 4D : <caret/></text>        
    </macro>
    
    <macro name="Commenter/j"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_runMacro("comment")</method></text>
    </macro>
    
    <macro name="Dupliquer et commenter/∂" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("duplicateAndComment")</method></text>    
    </macro>
    
    <!-- ******************************* REFACTORING ******************************* -->
    <macro name="-" type_ahead="false"><text/></macro>
    
    <macro name="Assertion conditionelle/æ" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("Asserted")</method></text>
    </macro>
    
    <macro name="Convertir en appel avec token" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("ConvertToCallWithToken")</method></text>
    </macro>
    
    <macro name="Notation à point" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("dot_notation")</method></text>
    </macro>
    
    <macro name="Choisir" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("Choose")</method></text>        
    </macro>
    
    <macro name="EXECUTER METHODE" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("convert_to_execute")</method></text>        
    </macro>
    
    <macro name="EXECUTER FORMULE" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("convert_to_formula")</method></text>        
    </macro> 
       
    <!-- ******************************* CONVERSIONS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Maquereau 4D : mdr">
        <text>Scomber scombrus : <caret/></text>
    </macro>
    
    <macro name="Convertir en Hexa" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("convert_hexa")</method></text>        
    </macro>
    
    <macro name="Convertir en decimal" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("convert_decimal")</method></text>        
    </macro>
    
    <macro name="-"  in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Expression inverse" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("invert_expression")</method></text>        
    </macro>

    <macro name="-"  in_menu="true" type_ahead="false"><text/></macro>
        
</macros>

=== vdelachaux/4DPop-Macros/Resources/4DPop_Macros.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE macros SYSTEM "http://www.4d.com/dtd/2007/macros.dtd" >

<!--
    4DPop macros - [EN]
    vincent@de-lachaux.net
-->

<macros>
    
    <!-- ******************************* TOOLS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Macro test/0" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>4DPop_TEST_Macros</method></text>
    </macro>
    
    <macro name="Replay the last macro run" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro</method></text>
    </macro>
    
    <macro name="Declarations.../$" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("Declarations";"<method_path/>")</method></text>
    </macro>
    
    <macro name="Compiler directive… /¢" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
         <text><method>_runMacro("compiler_directive")</method></text>
    </macro>
    
    <macro name="Constant value…" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("constantValue")</method></text>
    </macro>
    
    <macro name="Find with Google" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("googleSearch")</method></text>
    </macro>
    
    <macro name="Make an archive" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("zipForShare")</method></text>
    </macro>
    
    <!-- ******************************* METHODS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
        
    <macro name="New method…/…" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_method" 
        version="2">        
        <text><method>_runMacro("method-new")</method></text>        
    </macro>
        
    <macro name="Method attributes…" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_attributes" 
        version="2">        
        <text><method>_runMacro("method-attributes";"<method_path/>")</method></text>        
    </macro>
        
    <macro name="Beautifier/§" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("Beautifier")</method></text>        
    </macro>
    
    <macro name="Remove blank lines/*" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("RemoveBlankLines")</method></text>        
    </macro>
    
    <!-- ******************************* COPY PASTE ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Scomber scombrus : lol">
        <text><method>_runMacro("about")</method></text>
    </macro>
    
    <macro name="Copy with tokens"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_runMacro("CopyWithTokens")</method></text>
    </macro>
    
    <macro name="Copy and replace/©" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("PasteAndKeepTarget")</method></text>
    </macro>
    
    <macro name="Special paste.../◊" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_p"
        version="2">
        <text><method>_runMacro("SpecialPaste")</method></text>
    </macro>
    
    <macro name="Past a color expression" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_c"
        version="2">
        <text><method>_runMacro("PasteColor")</method></text>
    </macro>
    
    <!-- ******************************* COMMENTS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="4d macro">
        <text>Maquereau 4D : <caret/></text>        
    </macro>

    <macro name="Comments/j"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_runMacro("comment")</method></text>
    </macro>
    
    <macro name="Duplicate and comment/∂"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_runMacro("duplicateAndComment")</method></text>
    </macro>
    
    <!-- ******************************* REFACTORING ******************************* -->
    <macro name="-" type_ahead="false"><text/></macro>
    
    <macro name="Conditional assertion/æ" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("Asserted")</method></text>
    </macro>
    
    <macro name="Convert to call with token" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("ConvertToCallWithToken")</method></text>
    </macro>
    
    <macro name="Dot notation" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("dot_notation")</method></text>
    </macro>
    
    <macro name="Choose" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("Choose")</method></text>        
    </macro>
    
    <macro name="EXECUTE METHOD" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("convert_to_execute")</method></text>        
    </macro>
    
    <macro name="EXECUTE FORMULA" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_runMacro("convert_to_formula")</method></text>        
    </macro>
        
    <!-- ******************************* CONVERSIONS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Maquereau 4D : mdr">
        <text>Scomber scombrus : <caret/></text>
    </macro>
    
    <macro name="Convert to Hexa" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("convert_hexa")</method></text>
    </macro>
    
    <macro name="Convert to decimal" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("convert_decimal")</method></text>
    </macro>
    
    <macro name="-" type_ahead="false"><text/></macro>
    
    <macro name="Invert expression" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_runMacro("invert_expression")</method></text>
    </macro>
    
    <macro name="-"  in_menu="true" type_ahead="false"><text/></macro>
    
</macros>
