=== vdelachaux/4DPop-Macros/Build/Components/4DPop Macros.4dbase/Contents/Resources/macros.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--Grammar for 4th Dimension methods macros. 4D SA.-->

<!-- caret position after macro expansion -->
<!ELEMENT caret EMPTY>

<!-- placeholder for selection -->
<!ELEMENT selection EMPTY>

<!-- placeholder for operating system user name -->
<!ELEMENT user_os EMPTY>

<!-- placeholder for 4D user name -->
<!ELEMENT user_4d EMPTY>

<!-- placeholder for method name -->
<!ELEMENT method_name EMPTY>

<!-- placeholder for method path -->
<!ELEMENT method_path EMPTY>

<!-- placeholder for current time -->
<!-- format = 0 to 8 -->
<!ELEMENT time EMPTY>
<!ATTLIST time format CDATA #IMPLIED>

<!-- placeholder for current date -->
<!-- format = 0 to 6 -->
<!ELEMENT date EMPTY>
<!ATTLIST date format CDATA #IMPLIED>

<!-- placeholder for clipboard contents -->
<!-- index = 0 to 9 -->
<!ELEMENT clipboard EMPTY>
<!ATTLIST clipboard index CDATA #IMPLIED>

<!-- method contents -->
<!ELEMENT method (#PCDATA | user_os | user_4d | time | date | method_name | method_path | caret | selection | clipboard )*>

<!-- macro contents -->
<!ELEMENT text (#PCDATA | user_os | user_4d | time | date | method_name | method_path | caret | selection | method | clipboard )*>

<!-- macro -->
<!-- name = name as displayed in contextual menu -->
<!-- type_ahead_text = text to type to activate the macro using type ahead (default is the macro name) -->
<!-- type_ahead = should this macro be available using type ahead? (default is true) -->
<!-- note: if the macro contents uses the selection placeholder, it cannot be activated using type-ahead -->
<!-- in_menu = should this macro be displayed in contextual menu? (default is true) -->
<!-- method_event can be on_create, on_save, on_load, on_close, on_tab -->
<!-- version: if version is equal to 2, macro can use SET/GET MACRO PARAMETER method -->
<!ELEMENT macro (text?)>
<!ATTLIST macro
  name CDATA #REQUIRED
  type_ahead_text CDATA #IMPLIED
  type_ahead (true | false) "true"
  in_menu (true | false) "true"
  in_toolbar (true | false) "true"
  method_event CDATA #IMPLIED
  version CDATA #IMPLIED
>
<!-- a macro file contains macros -->
<!ELEMENT macros (#PCDATA | macro)*>

=== vdelachaux/4DPop-Macros/Build/Components/4DPop Macros.4dbase/Contents/Resources/fr.lproj/4DPop_Macros.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE macros SYSTEM "http://www.4d.com/dtd/2007/macros.dtd" >

<!--
    4DPop macros - [FR]
    vincent@de-lachaux.net
-->

<macros>
    
    <!-- ******************************* OUTILS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Test Macro/0" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>4DPop_TEST_Macros</method></text>        
    </macro>
    
    <macro name="Rejouer la dernière macro exécutée" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS</method></text>        
    </macro>
    
    <macro name="Déclarations.../$" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("Declarations";"<method_path/>")</method></text>        
    </macro>
    
    <macro name="Directive de compilation… /¢" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("compiler_directive")</method></text>
    </macro>
    
    <macro name="Valeur de la constante…" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("constantValue")</method></text>
    </macro>
    
    <macro name="Chercher avec Google" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("googleSearch")</method></text>
    </macro>
    
    <macro name="Faire une archive" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("zipForShare")</method></text>
    </macro>
    
    <!-- ******************************* METHODS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Nouvelle méthode…/…" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_method" 
        version="2">        
        <text><method>_4DPop_MACROS("method-new")</method></text>        
    </macro>
    
    <macro name="Beautifier/§" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("Beautifier")</method></text>        
    </macro>
    
    <macro name="Supprimer les lignes vides/*" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("RemoveBlankLines")</method></text>        
    </macro>
    
    <!-- ******************************* COPIER COLLER ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Scomber scombrus : lol">
        <text><method>_4DPop_MACROS("about")</method></text>
    </macro>
    
    <macro name="Copie avec tokens"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_4DPop_MACROS("CopyWithTokens")</method></text>
    </macro>
    
    <macro name="Copier et Remplacer/©" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("PasteAndKeepTarget")</method></text>        
    </macro>
    
    <macro name="Collage spécial.../◊" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_p" 
        version="2">        
        <text><method>_4DPop_MACROS("SpecialPaste")</method></text>        
    </macro>
    
    <macro name="Coller une couleur" 
        in_menu="true" 
        type_ahead="true" 
        type_ahead_text="_c" 
        version="2">        
        <text><method>_4DPop_MACROS("PasteColor")</method></text>        
    </macro>  
    
    <!-- ******************************* COMMENTAIRES ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="4d macro">
        <text>Maquereau 4D : <caret/></text>        
    </macro>
    
    <macro name="Commenter/j"
        in_menu="true"
        type_ahead="false"
        version="2">
        <text><method>_4DPop_MACROS("comment")</method></text>
    </macro>
    
    <macro name="Dupliquer et commenter/∂" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("duplicateAndComment")</method></text>    
    </macro>
    
    <!-- ******************************* REFACTORING ******************************* -->
    <macro name="-" type_ahead="false"><text/></macro>
    
    <macro name="Assertion conditionelle/æ" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("Asserted")</method></text>
    </macro>
    
    <macro name="Convertir en appel avec token" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("ConvertToCallWithToken")</method></text>
    </macro>
    
    <macro name="Notation à point" 
        in_menu="true" 
        type_ahead="false" 
        version="2">
        <text><method>_4DPop_MACROS("dot_notation")</method></text>
    </macro>
    
    <macro name="Choisir" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("Choose")</method></text>        
    </macro>
    
    <macro name="EXECUTER METHODE" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("convert_to_execute")</method></text>        
    </macro>
    
    <macro name="EXECUTER FORMULE" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("convert_to_formula")</method></text>        
    </macro> 
       
    <!-- ******************************* CONVERSIONS ******************************* -->
    <macro name="-" in_menu="true" type_ahead="true" type_ahead_text="Maquereau 4D : mdr">
        <text>Scomber scombrus : <caret/></text>
    </macro>
    
    <macro name="Convertir en Hexa" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("convert_hexa")</method></text>        
    </macro>
    
    <macro name="Convertir en decimal" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("convert_decimal")</method></text>        
    </macro>
    
    <macro name="-"  in_menu="true" type_ahead="false"><text/></macro>
    
    <macro name="Expression inverse" 
        in_menu="true" 
        type_ahead="false" 
        version="2">        
        <text><method>_4DPop_MACROS("invert_expression")</method></text>        
    </macro>

    <macro name="-"  in_menu="true" type_ahead="false"><text/></macro>
        
</macros>
